### PR TITLE
decorators added

### PR DESCRIPTION
**Pull request by AnotherCodeArtist**
I had an issue with some options that are very long and therefore did not fit on the screen properly. That's how I came up with the idea to add a decorator function that can be used the modify (e.g. shorten) the displayed value. It could be used to apply any transformation and can also add additional ReactNode elements.

grafik

Here's the `selectedValueDecorator` in action:
grafik

### CODE REVIEW

**Comment by srigar** [comment]
Will check and release it

**Review by srigar — APPROVED** [review]

**Comment by srigar** [comment]
@AnotherCodeArtist Pls resolve conflicts

**Comment by AnotherCodeArtist** [comment]
Conflicts resolved

**Comment by srigar** [comment]
Changes available in v2.0.24

**Pull request merged**
