### PR TITLE
Missing loading property fixed

### PR DESCRIPTION
**Pull request by AnotherCodeArtist**
Although mentioned in the documentation, the `loading` property was missing in `IMultiselectProps` and therefore could not be used in a typescript environment.
Additionally a story was added, that demonstrate the use of asynchronous data loading.

### CODE REVIEW

**Comment by AnotherCodeArtist** [comment]
No way to see what's wrong with the build, since I get a 404 from Vercel.

**Review by srigar — COMMENTED** [review]
already package-lock is there. Pls delete yarn.lock file

**Comment by AnotherCodeArtist** [comment]
Fixes #168

**Comment by AnotherCodeArtist** [comment]
Any reason why not merging it? I'd really like to upgrade to version 2.x, but my app relies on asynchronous queries (see [here](https://medien-transparenz.at/flows?pType=2&organisations=Bundeskanzleramt&from=20212&to=20212))

**Comment by srigar** [comment]
Changes available v2.0.8

**Pull request merged**
